# Updates the Gradle Cache when necessary
name: Update Gradle Cache

on:
  push:
    branches:
      - main
    paths: ['gradle/**', '**.gradle', 'gradle.properties', 'gradlew**']
  workflow_dispatch:

concurrency:
  group: gradle-cache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-cache:
    name: Update Gradle Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Build
        uses: ./.github/actions/build_setup
        with:
          update-cache: true

      - name: Build Project with Gradle
        run: ./gradlew --info --stacktrace assemble
